[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "netlify"
  NODE_VERSION = "20"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
