/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrompterRouteImport } from './routes/prompter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as CastRouteImport } from './routes/cast'
import { Route as IndexRouteImport } from './routes/index'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrompterRoute = PrompterRouteImport.update({
  id: '/prompter',
  path: '/prompter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const CastRoute = CastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/document': typeof DocumentRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/prompter': typeof PrompterRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/document': typeof DocumentRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/prompter': typeof PrompterRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cast': typeof CastRoute
  '/document': typeof DocumentRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/prompter': typeof PrompterRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cast'
    | '/document'
    | '/files'
    | '/login'
    | '/prompter'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cast'
    | '/document'
    | '/files'
    | '/login'
    | '/prompter'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/cast'
    | '/document'
    | '/files'
    | '/login'
    | '/prompter'
    | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CastRoute: typeof CastRoute
  DocumentRoute: typeof DocumentRoute
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  PrompterRoute: typeof PrompterRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompter': {
      id: '/prompter'
      path: '/prompter'
      fullPath: '/prompter'
      preLoaderRoute: typeof PrompterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast': {
      id: '/cast'
      path: '/cast'
      fullPath: '/cast'
      preLoaderRoute: typeof CastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CastRoute: CastRoute,
  DocumentRoute: DocumentRoute,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  PrompterRoute: PrompterRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
